### ISSUE TITLE
Broadcast grids within a specified area (distance from position?)

### ISSUE THREAD

**Issue by BookBurner** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#1]
Hello there

Idea behind it is to mark ships approaching a specified location (such as a planet with a rare resource for example) and thus making it more dangerous.

If there is cost involved with development of such an upgrade, I am willing to cover as much of it as I am able.

BookBurner
jakubuselik@gmail.com

**Comment by LordTylus** [comment]
Added it to v1.0.2.1 

![image](https://user-images.githubusercontent.com/22499516/78499808-19610100-7753-11ea-8002-bf4aef8ca320.png)

Have fun :-)

**Comment by BookBurner** [comment]
@LordTylus where can I make some donation to you man? you are my hero, I am going to test it asap :)
