### ISSUE TITLE
[Feature request] Log addition

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#12]
```
10:11:06.0123 [INFO]   ALE_Biggest_Grids_Broadcast.GridsBroadcastPlugin: Removing Biggest Grid GPS from all Players.
10:11:06.0279 [INFO]   ALE_Biggest_Grids_Broadcast.Commands: Broadcasted 90148860029296822 Tachi DRACONIS Owned by: Espeque [INF]
10:11:06.0279 [INFO]   Torch.Commands.CommandManager: Server ran command '!sendmixgps true true'
```
Would you please add to the "Broadcasted" line the reason it was broadcast? Even just a single word to tell between pcu/blockcount/distance/etc

**Comment by LordTylus** [comment]
Done. 

![image](https://user-images.githubusercontent.com/22499516/113481620-cd968400-949a-11eb-849b-e0a6055fd3ec.png)

Will be added in v1.0.6.3
