### ISSUE TITLE
Not count Grids connected to inspected grid by Landing Gear. "BUG"

### ISSUE THREAD

**Issue by dorimanx** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#16]
Hi,

Right now code count grid blocks, by looking at the grid and count all blocks + blocks of other ships connected by landing gear to inspected grid.
as game see this grid as 1 grid.
but in game we can see that we have 5 fighters on landing gears connected to large ship with 6K blocks. and little fighters add more 3k Blocks, and large ship get marked as TOP grid if setting is set to show grids with 8K blocks.

**Comment by LordTylus** [comment]
Hi,

this should not be possible. I Only Check for Physical and Mechanical connections based on the plugin settings.

Connections through landing gear should always be ignored. Can you provide me with a Blueprint, or a Test world for easier reproduction?

And some screenshots maybe of the grids in question, (especially info tab) and which exact command you running as well as your plugin config? 

Thanks :-)

**Comment by LordTylus** [comment]
Tried Reproducing:

Set Min Blocks to 500
and Used !listbigblockgrids

connection via landing gear does not show the grid
the station has 499 blocks and the ship 120

https://cdn.discordapp.com/attachments/360599679714590743/882359827261698088/unknown.png
https://cdn.discordapp.com/attachments/360599679714590743/882359905963614339/unknown.png

If I disconnect the ship and just add one refinery (the 500th block)
https://cdn.discordapp.com/attachments/360599679714590743/882360200210825286/unknown.png
https://cdn.discordapp.com/attachments/360599679714590743/882360228778217552/unknown.png

it shows up just fine. So its working as intended no bug found.

**Comment by dorimanx** [comment]
hmm.
I see when i add ship on top of other ship with landing gear, my small ship is consumed, and no longer in ships list, but the mail ship gaining blocks

**Comment by dorimanx** [comment]
![added 1 ship-landing gear](https://user-images.githubusercontent.com/1135626/131571684-bd57c84d-4fce-4a12-b715-09a3eeff05e4.JPG)
![2-ships](https://user-images.githubusercontent.com/1135626/131571688-b496a983-e529-4246-b828-dd89755e09aa.JPG)
![1-ship-Large_and_Small_connected](https://user-images.githubusercontent.com/1135626/131571690-887e9251-4d60-4445-8d79-cea3420c74bc.JPG)

**Comment by dorimanx** [comment]
![add ship](https://user-images.githubusercontent.com/1135626/131571898-1c11cb5b-94d5-4236-8874-11ceea1a7149.JPG)

**Comment by dorimanx** [comment]
i will do more tests, thank you for your time.

**Comment by LordTylus** [comment]
Do you use any Mod or Plugin that might "merge" grids like that for stability or performance?

Especially if its big and small ship it sounds like supergridding to me. 

In that case it would not be a bug in Gridbroadcast but a side effect of whatever you are using that causes that and I wouldnt be able to fix it.

when I connect my grids I get: 
![image](https://user-images.githubusercontent.com/22499516/131572162-3475179b-6560-4b9a-a2af-3a538a74cc18.png)
![image](https://user-images.githubusercontent.com/22499516/131572203-67a73d59-bce2-4bea-9cc5-3a64bf55d6f2.png)

which looks as it is supposed to

**Comment by dorimanx** [comment]
check with dedicate Vrage Remote client. it's shows grid as 1, and supergriding is off.
i am doing tests to understand what can that be.

**Comment by dorimanx** [comment]
Ok, i have done some tests, and i cant make it to mark my ship, with one more ship on landing gear, or connected via connector.
not sure what was the issue before, but it's gone.
If i will even able to trigger it, i will provide more info.
Thanks.
