### ISSUE TITLE
Broadcast Abandoned Bases

### ISSUE THREAD

**Issue by blthlt** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#2]
Can we add the option to broadcast abandoned bases if owner last logout over "X" days.

**Comment by LordTylus** [comment]
Great Idea

**Comment by blthlt** [comment]
I think at that point, the faction needs to keep track of their people and grind their blocks down and replace them.  This will incite PVP on my server as I'm sure it will on others when people go to get the "free" goodies.

**Comment by LordTylus** [comment]
Added in v1.0.3.1 

there is now
!listabandonedgrids
!sendabandonedgps

and sendmixgps has a new parameter that allows sending abandoned grids along with biggest or furthest or both.

you can configure the days of which a grid counts as abandoned default is 10 days
and you can configure if you only want to look at the direct owner of the biggest grid of a group

or if you want to also look on ALL members of the faction. To basically mark something as abandoned when the whole faction is gone for x days. 

up to you
