### ISSUE TITLE
Request: Configure type of Grid Broadcasting like Ship/Static Grids

### ISSUE THREAD

**Issue by SKO85** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#3]
Hi LordTylus,

I configured your plugin on my server but I wanted to have it only enabled for Ships and not mark stations to be broadcasted so only ships for example. So I thought I will post a request here to maybe make this configurable selectbox (true/false) for:

For grid types:
- Broadcast Stations: true/false
- Broadcast Ships: true/false

For sizes:
- Broadcast Large Grids: true/false
- Broadcast Small Grids: true/false

Thanks for the great work!
SKO85

**Comment by LordTylus** [comment]
So completely ignore Stations for example?

Meaning the Top X will only be determined by Ships right?

I mean if the Top X are all stations otherwise nothing would be broadcasted at all if turned off.

**Comment by LordTylus** [comment]
Added in v1.0.4.0
