### ISSUE TITLE
Feature Request: Block # instead of PCU #

### ISSUE THREAD

**Issue by Fowlplaychiken** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#5]
Feature request; will throw a few bucks your way in gratitude. 

I would like to disable PCU feature. Instead, I would like to broadcast any grid over 10,000 blocks, including subgrids, connector attached grids, landing gear attached grids. If the whole spaghetti is over 10,000 blocks, broadcast its location until its under. The feature someone else requested to also disable any safezone they have is also nice ;)

**Comment by dorimanx** [comment]
Sounds great! as many servers dont use PCU. just block limits.
And we can combine 2 checks, high PCU and amount of blocks!

**Comment by LordTylus** [comment]
Added a new parameter to sendmixgps
added dedicated commands for !sendbigblockgps

mostly due to backwards compatibility so I dont change any already existing settings for users.

works fine. can be used in 1.0.6.0
