### ISSUE TITLE
Possible BUG: when marked ship is destroyed there is crash without logs.

### ISSUE THREAD

**Issue by dorimanx** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#7]
Hi,

Today i have seen strange situation, player found other player that was marked by plugin and with follow GPS.
he arrived and destroyed the marked ship, then server hit the !removegps
and torch just closed without any log... just poof.. no restart... no logs..

`
2020/06/11 12:31:49.363 [INFO]   Chat: [Global:0] sergeyman2020: да уж не красиво получилось
2020/06/11 12:32:09.703 [INFO]   ALE_Biggest_Grids_Broadcast.GridsBroadcastPlugin: Removing Biggest Grid GPS from all Players.
2020/06/11 12:32:09.703 [INFO]   Torch.Commands.CommandManager: Server ran command '!removegps'
2020/06/11 12:39:39.554 [INFO]   SteamCMD: Checking for DS updates.
2020/06/11 12:39:40.730 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
2020/06/11 12:39:40.831 [INFO]   SteamCMD: -- type 'quit' to exit --
2020/06/11 12:39:40.932 [INFO]   SteamCMD: Loading Steam API...OK.

`

**Comment by LordTylus** [comment]
Hi thank you for the Report.

Not sure why that happens, but will take a look right now

**Comment by LordTylus** [comment]
I tried to reproduce the Issue sadly I cannot find any errors. 

Torch Command system should capture all failed commands also. So I am not sure whats the issue. Can you give me the exact steps to reproduce?

**Comment by dorimanx** [comment]
I have tried to make such crash again and i cant. so it's was something else.
Closing issue.
Thank you for your work!
