### ISSUE TITLE
Feature request: Log entry that lists grids included in a broadcast

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#8]
I would like to see a log entry for what grids are broadcast when the !send*gps command is fired off please.  We have lots of pvp incidents that say "We found them because they top grid!" and it'd be nice as staff to be able to put a foot down and say "but it never did!" or so forth

**Comment by LordTylus** [comment]
Just an Info Log with hey following grids are sent out?

easy Will do.

**Comment by LordTylus** [comment]
Added in 1.0.5.2
![image](https://user-images.githubusercontent.com/22499516/84568746-d5f1c700-ad81-11ea-94ba-27102dae8caa.png)

Have fun
